name: Pr validation

on: pull_request

jobs:
  job1:
    name: first job 
    runs-on: ubuntu-latest
    steps:
    - name: steps 1
      uses: actions/checkout@v4
    - name: step 2
      run: echo "hellow"
  
