name: Pr-validation

on: 
  pull_request:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      TOKEN: "ola"
    steps:
    - name: checkout the branch
      uses: actions/checkout@v4
      with:
        path: ./download
    - name: print the env variables
      run: env    
    - name: execute the commands below and print env variable and secrets
      run: |
        ls -lthr ./download
        echo "${{ secrets.VERSION }}"
        echo "${{ env.TOKEN }}"
    - name: print hellow
      run: echo "hellow"
    - name: Python Syntax Checker
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
