name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.VERSION }}
        run: |
          echo "$SUPER_SECRET"

